### ISSUE TITLE
Presto not working after adding Teradata connector jars in plugin folder

### ISSUE THREAD

**Issue by odeshman** [jmrozanec/presto-teradata-connector#2]
Hi Jose,
Thank you for this repo. I am using this to build Teradata connector jars and was able to build. But, when I keep these jars in plugin folder under Presto installation directory, Presto server stops working with below error-

2016-07-28T16:00:52.729-0400    INFO    main    com.facebook.presto.server.PluginManager        Installing com.facebook.presto.plugin.teradata.TeradataPlugin
2016-07-28T16:00:52.751-0400    INFO    main    com.facebook.presto.server.PluginManager        Registering legacy connector teradata
2016-07-28T16:00:52.752-0400    ERROR   main    com.facebook.presto.server.PrestoServer null
java.lang.AbstractMethodError
        at com.facebook.presto.transaction.LegacyTransactionConnectorFactory.getHandleResolver(LegacyTransactionConnectorFactory.java:43)
        at com.facebook.presto.connector.ConnectorManager.addConnectorFactory(ConnectorManager.java:140)
        at com.facebook.presto.connector.ConnectorManager.addConnectorFactory(ConnectorManager.java:132)
        at com.facebook.presto.server.PluginManager.installPlugin(PluginManager.java:211)
        at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:184)
        at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:167)
        at com.facebook.presto.server.PluginManager.loadPlugins(PluginManager.java:148)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:113)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:63)

I am trying to debug the issue, but thought you may be able to help if I am missing any step while build. Your help is really appreciated.

Thank you.

**Comment by jmrozanec** [comment]
@odeshman Thank you for reaching us! are you using the same Presto version this code was written for? We wrote it for version 0.130

**Comment by jmrozanec** [comment]
@odeshman could you solve the issue?

**Comment by jmrozanec** [comment]
@odeshman please let me know if the issue was solved or any help can be provided to do so. If no response is given, will close the issue by end of week. Thanks!

**Comment by jmrozanec** [comment]
Closing since we got no update.
