### ISSUE TITLE
Installing on presto 175

### ISSUE THREAD

**Issue by doug2525** [jmrozanec/presto-teradata-connector#5]
Still receiving errors trying to use the connector with presto 175. I may be missing something but I am receiving errors in the presto log when starting the server. I used the 15.10 drivers when building the package. I copied the set of jars from the plugin/postgres directory in presto into the plugin/teradata directory and added all 3 jars into it. 

When I start presto I can see in the logs that it starts up the connector but soon gets the error below.

2017-10-09T18:21:29.396Z	INFO	main	Bootstrap	
2017-10-09T18:21:30.247Z	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2017-10-09T18:21:30.247Z	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle startup complete. System ready.
2017-10-09T18:21:30.250Z	INFO	main	com.facebook.presto.metadata.StaticCatalogStore	-- Added catalog kafkaj using connector kafka --
2017-10-09T18:21:30.250Z	INFO	main	com.facebook.presto.metadata.StaticCatalogStore	-- Loading catalog etc/catalog/teradata.properties --
2017-10-09T18:21:30.695Z	INFO	main	Bootstrap	PROPERTY             DEFAULT  RUNTIME                                             DESCRIPTION
2017-10-09T18:21:30.695Z	INFO	main	Bootstrap	connection-password  null     *****
2017-10-09T18:21:30.695Z	INFO	main	Bootstrap	connection-url       null     jdbc:teradata://********/TMODE=ANSI,CHARSET=UTF8
2017-10-09T18:21:30.695Z	INFO	main	Bootstrap	connection-user      null     ******
2017-10-09T18:21:30.695Z	INFO	main	Bootstrap	allow-drop-table     false    false                                               Allow connector to drop tables
2017-10-09T18:21:30.695Z	INFO	main	Bootstrap	teradata.password    null     null
2017-10-09T18:21:30.695Z	INFO	main	Bootstrap	teradata.url         null     null
2017-10-09T18:21:30.695Z	INFO	main	Bootstrap	teradata.user        null     null
2017-10-09T18:21:30.695Z	INFO	main	Bootstrap	
2017-10-09T18:21:31.044Z	ERROR	main	com.facebook.presto.server.PrestoServer	Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: com/teradata/jdbc/TeraDriver
  at com.facebook.presto.plugin.teradata.TeradataClient.<init>(TeradataClient.java:56)
  while locating com.facebook.presto.plugin.teradata.TeradataClient
  at com.facebook.presto.plugin.teradata.TeradataClientModule.configure(TeradataClientModule.java:30)
  while locating com.facebook.presto.plugin.jdbc.JdbcClient
Caused by: java.lang.NoClassDefFoundError: com/teradata/jdbc/TeraDriver
	at com.facebook.presto.plugin.teradata.TeradataClient.<init>(TeradataClient.java:56)
	at com.facebook.presto.plugin.teradata.TeradataClient$$FastClassByGuice$$94e43dc6.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:242)
	at com.facebook.presto.plugin.jdbc.JdbcConnectorFactory.create(JdbcConnectorFactory.java:71)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:304)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:193)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:185)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:171)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:99)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:77)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:120)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
Caused by: java.lang.ClassNotFoundException: com.teradata.jdbc.TeraDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.facebook.presto.server.PluginClassLoader.loadClass(PluginClassLoader.java:76)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more

**Comment by doug2525** [comment]
For this step where is the "presto-dependencies" directory?

 To install the connector, copy presto-teradata-{version}.jar and jars at $PROJECT_HOME/presto-dependencies/ directory to some location, ex.: /tmp/teradata-jars/

**Comment by jmrozanec** [comment]
@doug2525 presto-dependencies is the lib directory. At the pom.xml configurations you may find it as a local repo, where you can set the required Teradata jars which are not offered from a public Maven repo. Please let us know if we can provide further clarifications.
