### ISSUE TITLE
The UserId, Password or Account is invalid.

### ISSUE THREAD

**Issue by doug2525** [jmrozanec/presto-teradata-connector#6]
Not sure what the issue is. I am able to connect with the credentials through teradata studio but when I use the same credentials with the presto connector I get this error:
`Query 20171206_194506_00007_tvmas failed: java.sql.SQLException: [Teradata Database] [TeraJDBC 15.10.00.35] [Error 8017] [SQLState 28000] The UserId, Password or Account is invalid.`
We can see the connection being made on the Teradata side so that part is working and the credentials have been double and triple checked. I'm wondering if you have ran into this before.

**Comment by jmrozanec** [comment]
@doug2525 we have not run into this before. Do we have some way to replicate the scenario? Was everything working ok and suddenly you started getting this error or is this a brand new installation?

**Comment by doug2525** [comment]
@jmrozanec we were just getting the connection setup. It is going against a Teradata cloud instance. I suspect that has something to do with it as I have a java program that worked up until they moved to the cloud instance and it is seeing the same error. We discovered that late yesterday afternoon. I can connect with Teradata studio with the same credentials it is just when I try to connect with the java program or the connector I get the error. The teradata guys are currently looking into it but I'll update this post when we find the solution.

**Comment by doug2525** [comment]
@jmrozanec well I attempted to update the teradata jdbc driver and rebuild the project. Now presto just crashes with the below error. I assume I am putting the files in the wrong spot for buiIding the project. I also pasted the steps I took to build the project below. Then I just copied the generated jar and the two teradata jars into the the presto/plugins/teradata directory.

**# 1. Errror being received:**

2017-12-07T19:40:08.496Z	ERROR	main	com.facebook.presto.server.PrestoServer	Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: com/teradata/jdbc/TeraDriver
  at com.facebook.presto.plugin.teradata.TeradataClient.<init>(TeradataClient.java:56)
  while locating com.facebook.presto.plugin.teradata.TeradataClient
  at com.facebook.presto.plugin.teradata.TeradataClientModule.configure(TeradataClientModule.java:30)
  while locating com.facebook.presto.plugin.jdbc.JdbcClient
Caused by: java.lang.NoClassDefFoundError: com/teradata/jdbc/TeraDriver
	at com.facebook.presto.plugin.teradata.TeradataClient.<init>(TeradataClient.java:56)
	at com.facebook.presto.plugin.teradata.TeradataClient$$FastClassByGuice$$94e43dc6.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:242)
	at com.facebook.presto.plugin.jdbc.JdbcConnectorFactory.create(JdbcConnectorFactory.java:71)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:304)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:193)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:185)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:171)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:99)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:77)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:120)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
Caused by: java.lang.ClassNotFoundException: com.teradata.jdbc.TeraDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.facebook.presto.server.PluginClassLoader.loadClass(PluginClassLoader.java:76)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more

**# 2. Steps taken for building the project and build log** 

C02MN016FD57:presto-teradata-connector datrox$ ls
LICENSE		README.md	pom.xml		src
C02MN016FD57:presto-teradata-connector datrox$ mkdir lib
C02MN016FD57:presto-teradata-connector datrox$ mkdir lib/com
C02MN016FD57:presto-teradata-connector datrox$ mkdir lib/com/teradata
C02MN016FD57:presto-teradata-connector datrox$ mkdir lib/com/teradata/config
C02MN016FD57:presto-teradata-connector datrox$ mkdir lib/com/teradata/config/15.10.0
C02MN016FD57:presto-teradata-connector datrox$ mkdir lib/com/teradata/jdbc/
C02MN016FD57:presto-teradata-connector datrox$ mkdir lib/com/teradata/jdbc/15.10.0
C02MN016FD57:presto-teradata-connector datrox$ cp /Users/datrox/Downloads/TeraJDBC__indep_indep.15.10.00.36/
readme.txt       tdgssconfig.jar  terajdbc4.jar    
C02MN016FD57:presto-teradata-connector datrox$ cp /Users/datrox/Downloads/TeraJDBC__indep_indep.15.10.00.36/tdgssconfig.jar lib/com/teradata/config/15.10.0/config-15.10.0.jar
C02MN016FD57:presto-teradata-connector datrox$ cp /Users/datrox/Downloads/TeraJDBC__indep_indep.15.10.00.36/tdgssconfig.jar lib/com/teradata/jdbc/15.10.0/jdbc-15.10.0.jar
C02MN016FD57:presto-teradata-connector datrox$ ls
LICENSE		README.md	lib		pom.xml		src
C02MN016FD57:presto-teradata-connector datrox$ mvn clean install
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building presto-teradata-connector 0.130.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: nexus address
Downloading: nexus address
Downloading: file:///Users/datrox/teradataconnector/presto-teradata-connector/lib/com/teradata/config/15.10.0/config-15.10.0.pom
[WARNING] The POM for com.teradata:config:jar:15.10.0 is missing, no dependency information available
Downloading: nexus address
Downloading: nexus address
Downloading: file:///Users/datrox/teradataconnector/presto-teradata-connector/lib/com/teradata/jdbc/15.10.0/jdbc-15.10.0.pom
[WARNING] The POM for com.teradata:jdbc:jar:15.10.0 is missing, no dependency information available
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ presto-teradata ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ presto-teradata ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ presto-teradata ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ presto-teradata ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 4 source files to /Users/datrox/teradataconnector/presto-teradata-connector/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ presto-teradata ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/datrox/teradataconnector/presto-teradata-connector/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ presto-teradata ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ presto-teradata ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ presto-teradata ---
[INFO] Building jar: /Users/datrox/teradataconnector/presto-teradata-connector/target/presto-teradata-0.130.2-SNAPSHOT.jar
[INFO] 
[INFO] >>> maven-source-plugin:2.2.1:jar (attach-sources) > generate-sources @ presto-teradata >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ presto-teradata ---
[INFO] 
[INFO] <<< maven-source-plugin:2.2.1:jar (attach-sources) < generate-sources @ presto-teradata <<<
[INFO] 
[INFO] 
[INFO] --- maven-source-plugin:2.2.1:jar (attach-sources) @ presto-teradata ---
[INFO] Building jar: /Users/datrox/teradataconnector/presto-teradata-connector/target/presto-teradata-0.130.2-SNAPSHOT-sources.jar
[INFO] 
[INFO] --- maven-javadoc-plugin:2.9.1:jar (attach-javadocs) @ presto-teradata ---
[INFO] 
Loading source files for package com.facebook.presto.plugin.teradata...
Constructing Javadoc information...
Standard Doclet version 1.8.0_111
Building tree for all the packages and classes...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/com/facebook/presto/plugin/teradata/TeradataClient.html...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/com/facebook/presto/plugin/teradata/TeradataClientModule.html...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/com/facebook/presto/plugin/teradata/TeradataConfig.html...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/com/facebook/presto/plugin/teradata/TeradataPlugin.html...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/com/facebook/presto/plugin/teradata/package-frame.html...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/com/facebook/presto/plugin/teradata/package-summary.html...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/com/facebook/presto/plugin/teradata/package-tree.html...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/constant-values.html...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/com/facebook/presto/plugin/teradata/class-use/TeradataPlugin.html...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/com/facebook/presto/plugin/teradata/class-use/TeradataConfig.html...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/com/facebook/presto/plugin/teradata/class-use/TeradataClientModule.html...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/com/facebook/presto/plugin/teradata/class-use/TeradataClient.html...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/com/facebook/presto/plugin/teradata/package-use.html...
Building index for all the packages and classes...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/overview-tree.html...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/index-all.html...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/deprecated-list.html...
Building index for all classes...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/allclasses-frame.html...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/allclasses-noframe.html...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/index.html...
Generating /Users/datrox/teradataconnector/presto-teradata-connector/target/apidocs/help-doc.html...
[INFO] Building jar: /Users/datrox/teradataconnector/presto-teradata-connector/target/presto-teradata-0.130.2-SNAPSHOT-javadoc.jar
[INFO] 
[INFO] --- maven-install-plugin:2.5.1:install (default-install) @ presto-teradata ---
[INFO] Installing /Users/datrox/teradataconnector/presto-teradata-connector/target/presto-teradata-0.130.2-SNAPSHOT.jar to /Users/datrox/.m2/repository/ml/prestoconnectors/presto-teradata/0.130.2-SNAPSHOT/presto-teradata-0.130.2-SNAPSHOT.jar
[INFO] Installing /Users/datrox/teradataconnector/presto-teradata-connector/pom.xml to /Users/datrox/.m2/repository/ml/prestoconnectors/presto-teradata/0.130.2-SNAPSHOT/presto-teradata-0.130.2-SNAPSHOT.pom
[INFO] Installing /Users/datrox/teradataconnector/presto-teradata-connector/target/presto-teradata-0.130.2-SNAPSHOT-sources.jar to /Users/datrox/.m2/repository/ml/prestoconnectors/presto-teradata/0.130.2-SNAPSHOT/presto-teradata-0.130.2-SNAPSHOT-sources.jar
[INFO] Installing /Users/datrox/teradataconnector/presto-teradata-connector/target/presto-teradata-0.130.2-SNAPSHOT-javadoc.jar to /Users/datrox/.m2/repository/ml/prestoconnectors/presto-teradata/0.130.2-SNAPSHOT/presto-teradata-0.130.2-SNAPSHOT-javadoc.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.231 s
[INFO] Finished at: 2017-12-07T13:10:13-06:00
[INFO] Final Memory: 35M/313M
[INFO] ------------------------------------------------------------------------

**Comment by crispkid** [comment]
I’ve rebuilt the Trino Teradata Connector for version 479.
[https://github.com/crispkid/trino-teradata](url)
