### ISSUE TITLE
presto-server-0.204 exception when loading teradata plugin

### ISSUE THREAD

**Issue by nolofson** [jmrozanec/presto-teradata-connector#7]
```
2018-06-18T15:23:36.415Z        INFO    main    com.facebook.presto.server.PluginManager        Registering connector sqlserver
2018-06-18T15:23:36.417Z        INFO    main    com.facebook.presto.server.PluginManager        -- Finished loading plugin /var/groupon/presto/data/plugin/sqlserver --
2018-06-18T15:23:36.417Z        INFO    main    com.facebook.presto.server.PluginManager        -- Loading plugin /var/groupon/presto/data/plugin/teradata --
2018-06-18T15:23:36.419Z        ERROR   main    com.facebook.presto.server.PrestoServer com/facebook/presto/plugin/jdbc/JdbcPlugin
java.lang.NoClassDefFoundError: com/facebook/presto/plugin/jdbc/JdbcPlugin
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at com.facebook.presto.server.PluginClassLoader.loadClass(PluginClassLoader.java:80)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:273)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:234)
        at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:164)
        at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:156)
        at com.facebook.presto.server.PluginManager.loadPlugins(PluginManager.java:137)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:117)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
Caused by: java.lang.ClassNotFoundException: com.facebook.presto.plugin.jdbc.JdbcPlugin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at com.facebook.presto.server.PluginClassLoader.loadClass(PluginClassLoader.java:80)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

```

**Comment by crispkid** [comment]
I’ve rebuilt the Trino Teradata Connector for version 479.
[https://github.com/crispkid/trino-teradata](url)
